default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_app_development
  host: localhost
  port: 5432
  username: postgres
  password: password

test:
  <<: *default
  database: test_app_test
  host: localhost
  port: 5432
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>