default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_app_development
  host: 172.18.0.2
  port: 5432
  username: postgres
  password: password

test:
  <<: *default
  database: test_app_test
  host: 172.18.0.2
  port: 5432
  username: postgres
  password: password

production:
  <<: *default
  database: test_app_production
  host: 172.18.0.2
  port: 5432
  username: postgres
  password: password